// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation_projection.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyConversationProjection = `-- name: ApplyConversationProjection :exec
INSERT INTO conversation_projection (
    id, resource_url, thread_id, thread_title, recipients, message_author, message_text, message_posted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (id) DO UPDATE SET
    resource_url = EXCLUDED.resource_url,
    thread_id = EXCLUDED.thread_id,
    thread_title = EXCLUDED.thread_title,
    recipients = EXCLUDED.recipients,
    message_author = EXCLUDED.message_author,
    message_text = EXCLUDED.message_text,
    message_posted_at = EXCLUDED.message_posted_at
`

type ApplyConversationProjectionParams struct {
	ID              string
	ResourceUrl     string
	ThreadID        string
	ThreadTitle     string
	Recipients      []string
	MessageAuthor   string
	MessageText     string
	MessagePostedAt pgtype.Timestamptz
}

func (q *Queries) ApplyConversationProjection(ctx context.Context, arg ApplyConversationProjectionParams) error {
	_, err := q.db.Exec(ctx, applyConversationProjection,
		arg.ID,
		arg.ResourceUrl,
		arg.ThreadID,
		arg.ThreadTitle,
		arg.Recipients,
		arg.MessageAuthor,
		arg.MessageText,
		arg.MessagePostedAt,
	)
	return err
}

const getConversationProjection = `-- name: GetConversationProjection :one
SELECT id, resource_url, thread_id, thread_title, recipients, message_author, message_text, message_posted_at
FROM conversation_projection
WHERE id = $1
`

func (q *Queries) GetConversationProjection(ctx context.Context, id string) (ConversationProjection, error) {
	row := q.db.QueryRow(ctx, getConversationProjection, id)
	var i ConversationProjection
	err := row.Scan(
		&i.ID,
		&i.ResourceUrl,
		&i.ThreadID,
		&i.ThreadTitle,
		&i.Recipients,
		&i.MessageAuthor,
		&i.MessageText,
		&i.MessagePostedAt,
	)
	return i, err
}

const getProjectionCheckpoint = `-- name: GetProjectionCheckpoint :one
SELECT sequence FROM projection_checkpoint LIMIT 1
`

func (q *Queries) GetProjectionCheckpoint(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getProjectionCheckpoint)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const setProjectionCheckpoint = `-- name: SetProjectionCheckpoint :exec
UPDATE projection_checkpoint SET sequence = $1 WHERE sequence < $1
`

func (q *Queries) SetProjectionCheckpoint(ctx context.Context, sequence int64) error {
	_, err := q.db.Exec(ctx, setProjectionCheckpoint, sequence)
	return err
}
