// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation_outbox.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const enqueueConversationStartedOutboxEntry = `-- name: EnqueueConversationStartedOutboxEntry :exec
INSERT INTO conversation_outbox (
    sequence, event_type, conversation_id, thread_id, message_id, creator, resource_url, thread_title, author, recipients, message_text, occurred_at
) VALUES (
    $1, 'ConversationStarted', $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (sequence) DO NOTHING
`

type EnqueueConversationStartedOutboxEntryParams struct {
	Sequence       int64
	ConversationID string
	ThreadID       string
	MessageID      string
	Creator        pgtype.Text
	ResourceUrl    pgtype.Text
	ThreadTitle    pgtype.Text
	Author         string
	Recipients     []string
	MessageText    string
	OccurredAt     pgtype.Timestamptz
}

func (q *Queries) EnqueueConversationStartedOutboxEntry(ctx context.Context, arg EnqueueConversationStartedOutboxEntryParams) error {
	_, err := q.db.Exec(ctx, enqueueConversationStartedOutboxEntry,
		arg.Sequence,
		arg.ConversationID,
		arg.ThreadID,
		arg.MessageID,
		arg.Creator,
		arg.ResourceUrl,
		arg.ThreadTitle,
		arg.Author,
		arg.Recipients,
		arg.MessageText,
		arg.OccurredAt,
	)
	return err
}

const enqueueReplyPostedOutboxEntry = `-- name: EnqueueReplyPostedOutboxEntry :exec
INSERT INTO conversation_outbox (
    sequence, event_type, conversation_id, thread_id, message_id, author, message_text, occurred_at
) VALUES (
    $1, 'ReplyPosted', $2, $3, $4, $5, $6, $7
)
ON CONFLICT (sequence) DO NOTHING
`

type EnqueueReplyPostedOutboxEntryParams struct {
	Sequence       int64
	ConversationID string
	ThreadID       string
	MessageID      string
	Author         string
	MessageText    string
	OccurredAt     pgtype.Timestamptz
}

func (q *Queries) EnqueueReplyPostedOutboxEntry(ctx context.Context, arg EnqueueReplyPostedOutboxEntryParams) error {
	_, err := q.db.Exec(ctx, enqueueReplyPostedOutboxEntry,
		arg.Sequence,
		arg.ConversationID,
		arg.ThreadID,
		arg.MessageID,
		arg.Author,
		arg.MessageText,
		arg.OccurredAt,
	)
	return err
}

const listPendingOutboxEntries = `-- name: ListPendingOutboxEntries :many
SELECT sequence, event_type, conversation_id, thread_id, message_id, creator, resource_url, thread_title, author, recipients, message_text, occurred_at
FROM conversation_outbox
WHERE done_at IS NULL
ORDER BY sequence
`

type ListPendingOutboxEntriesRow struct {
	Sequence       int64
	EventType      string
	ConversationID string
	ThreadID       string
	MessageID      string
	Creator        pgtype.Text
	ResourceUrl    pgtype.Text
	ThreadTitle    pgtype.Text
	Author         string
	Recipients     []string
	MessageText    string
	OccurredAt     pgtype.Timestamptz
}

func (q *Queries) ListPendingOutboxEntries(ctx context.Context) ([]ListPendingOutboxEntriesRow, error) {
	rows, err := q.db.Query(ctx, listPendingOutboxEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingOutboxEntriesRow
	for rows.Next() {
		var i ListPendingOutboxEntriesRow
		if err := rows.Scan(
			&i.Sequence,
			&i.EventType,
			&i.ConversationID,
			&i.ThreadID,
			&i.MessageID,
			&i.Creator,
			&i.ResourceUrl,
			&i.ThreadTitle,
			&i.Author,
			&i.Recipients,
			&i.MessageText,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEntryDone = `-- name: MarkOutboxEntryDone :exec
UPDATE conversation_outbox SET done_at = now() WHERE sequence = $1
`

func (q *Queries) MarkOutboxEntryDone(ctx context.Context, sequence int64) error {
	_, err := q.db.Exec(ctx, markOutboxEntryDone, sequence)
	return err
}
