// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation_outbox.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const enqueueOutboxEntry = `-- name: EnqueueOutboxEntry :exec
INSERT INTO conversation_outbox (
    sequence, event_type, conversation_id, occurred_at, payload
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (sequence) DO NOTHING
`

type EnqueueOutboxEntryParams struct {
	Sequence       int64
	EventType      string
	ConversationID string
	OccurredAt     pgtype.Timestamptz
	Payload        []byte
}

func (q *Queries) EnqueueOutboxEntry(ctx context.Context, arg EnqueueOutboxEntryParams) error {
	_, err := q.db.Exec(ctx, enqueueOutboxEntry,
		arg.Sequence,
		arg.EventType,
		arg.ConversationID,
		arg.OccurredAt,
		arg.Payload,
	)
	return err
}

const listPendingOutboxEntries = `-- name: ListPendingOutboxEntries :many
SELECT sequence, event_type, conversation_id, occurred_at, payload
FROM conversation_outbox
WHERE done_at IS NULL
ORDER BY sequence
`

type ListPendingOutboxEntriesRow struct {
	Sequence       int64
	EventType      string
	ConversationID string
	OccurredAt     pgtype.Timestamptz
	Payload        []byte
}

func (q *Queries) ListPendingOutboxEntries(ctx context.Context) ([]ListPendingOutboxEntriesRow, error) {
	rows, err := q.db.Query(ctx, listPendingOutboxEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingOutboxEntriesRow
	for rows.Next() {
		var i ListPendingOutboxEntriesRow
		if err := rows.Scan(
			&i.Sequence,
			&i.EventType,
			&i.ConversationID,
			&i.OccurredAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEntryDone = `-- name: MarkOutboxEntryDone :exec
UPDATE conversation_outbox SET done_at = now() WHERE sequence = $1
`

func (q *Queries) MarkOutboxEntryDone(ctx context.Context, sequence int64) error {
	_, err := q.db.Exec(ctx, markOutboxEntryDone, sequence)
	return err
}
