// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation_outbox.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const enqueueConversationCreatedOutboxEntry = `-- name: EnqueueConversationCreatedOutboxEntry :exec
INSERT INTO conversation_outbox (
    sequence, event_type, conversation_id, creator, resource_url, occurred_at
) VALUES (
    $1, 'ConversationCreated', $2, $3, $4, $5
)
ON CONFLICT (sequence) DO NOTHING
`

type EnqueueConversationCreatedOutboxEntryParams struct {
	Sequence       int64
	ConversationID string
	Creator        pgtype.Text
	ResourceUrl    pgtype.Text
	OccurredAt     pgtype.Timestamptz
}

func (q *Queries) EnqueueConversationCreatedOutboxEntry(ctx context.Context, arg EnqueueConversationCreatedOutboxEntryParams) error {
	_, err := q.db.Exec(ctx, enqueueConversationCreatedOutboxEntry,
		arg.Sequence,
		arg.ConversationID,
		arg.Creator,
		arg.ResourceUrl,
		arg.OccurredAt,
	)
	return err
}

const enqueueMessagePostedOutboxEntry = `-- name: EnqueueMessagePostedOutboxEntry :exec
INSERT INTO conversation_outbox (
    sequence, event_type, conversation_id, thread_id, message_id, author, message_text, occurred_at
) VALUES (
    $1, 'MessagePosted', $2, $3, $4, $5, $6, $7
)
ON CONFLICT (sequence) DO NOTHING
`

type EnqueueMessagePostedOutboxEntryParams struct {
	Sequence       int64
	ConversationID string
	ThreadID       pgtype.Text
	MessageID      pgtype.Text
	Author         pgtype.Text
	MessageText    pgtype.Text
	OccurredAt     pgtype.Timestamptz
}

func (q *Queries) EnqueueMessagePostedOutboxEntry(ctx context.Context, arg EnqueueMessagePostedOutboxEntryParams) error {
	_, err := q.db.Exec(ctx, enqueueMessagePostedOutboxEntry,
		arg.Sequence,
		arg.ConversationID,
		arg.ThreadID,
		arg.MessageID,
		arg.Author,
		arg.MessageText,
		arg.OccurredAt,
	)
	return err
}

const enqueueThreadStartedOutboxEntry = `-- name: EnqueueThreadStartedOutboxEntry :exec
INSERT INTO conversation_outbox (
    sequence, event_type, conversation_id, thread_id, thread_title, author, recipients, occurred_at
) VALUES (
    $1, 'ThreadStarted', $2, $3, $4, $5, $6, $7
)
ON CONFLICT (sequence) DO NOTHING
`

type EnqueueThreadStartedOutboxEntryParams struct {
	Sequence       int64
	ConversationID string
	ThreadID       pgtype.Text
	ThreadTitle    pgtype.Text
	Author         pgtype.Text
	Recipients     []string
	OccurredAt     pgtype.Timestamptz
}

func (q *Queries) EnqueueThreadStartedOutboxEntry(ctx context.Context, arg EnqueueThreadStartedOutboxEntryParams) error {
	_, err := q.db.Exec(ctx, enqueueThreadStartedOutboxEntry,
		arg.Sequence,
		arg.ConversationID,
		arg.ThreadID,
		arg.ThreadTitle,
		arg.Author,
		arg.Recipients,
		arg.OccurredAt,
	)
	return err
}

const listPendingOutboxEntries = `-- name: ListPendingOutboxEntries :many
SELECT sequence, event_type, conversation_id, thread_id, message_id, creator, resource_url, thread_title, author, recipients, message_text, occurred_at
FROM conversation_outbox
WHERE done_at IS NULL
ORDER BY sequence
`

type ListPendingOutboxEntriesRow struct {
	Sequence       int64
	EventType      string
	ConversationID string
	ThreadID       pgtype.Text
	MessageID      pgtype.Text
	Creator        pgtype.Text
	ResourceUrl    pgtype.Text
	ThreadTitle    pgtype.Text
	Author         pgtype.Text
	Recipients     []string
	MessageText    pgtype.Text
	OccurredAt     pgtype.Timestamptz
}

func (q *Queries) ListPendingOutboxEntries(ctx context.Context) ([]ListPendingOutboxEntriesRow, error) {
	rows, err := q.db.Query(ctx, listPendingOutboxEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingOutboxEntriesRow
	for rows.Next() {
		var i ListPendingOutboxEntriesRow
		if err := rows.Scan(
			&i.Sequence,
			&i.EventType,
			&i.ConversationID,
			&i.ThreadID,
			&i.MessageID,
			&i.Creator,
			&i.ResourceUrl,
			&i.ThreadTitle,
			&i.Author,
			&i.Recipients,
			&i.MessageText,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEntryDone = `-- name: MarkOutboxEntryDone :exec
UPDATE conversation_outbox SET done_at = now() WHERE sequence = $1
`

func (q *Queries) MarkOutboxEntryDone(ctx context.Context, sequence int64) error {
	_, err := q.db.Exec(ctx, markOutboxEntryDone, sequence)
	return err
}
