// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation_projection.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationProjectionThreadParticipant = `-- name: AddConversationProjectionThreadParticipant :exec
UPDATE conversation_projection_threads
SET participants = array_append(participants, $3::text)
WHERE conversation_id = $1 AND id = $2
`

type AddConversationProjectionThreadParticipantParams struct {
	ConversationID string
	ID             string
	Participant    string
}

func (q *Queries) AddConversationProjectionThreadParticipant(ctx context.Context, arg AddConversationProjectionThreadParticipantParams) error {
	_, err := q.db.Exec(ctx, addConversationProjectionThreadParticipant, arg.ConversationID, arg.ID, arg.Participant)
	return err
}

const appendConversationProjectionMessage = `-- name: AppendConversationProjectionMessage :exec
INSERT INTO conversation_projection_messages (
    conversation_id, thread_id, sequence, author, message_text, posted_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (conversation_id, sequence) DO NOTHING
`

type AppendConversationProjectionMessageParams struct {
	ConversationID string
	ThreadID       string
	Sequence       int64
	Author         string
	MessageText    string
	PostedAt       pgtype.Timestamptz
}

func (q *Queries) AppendConversationProjectionMessage(ctx context.Context, arg AppendConversationProjectionMessageParams) error {
	_, err := q.db.Exec(ctx, appendConversationProjectionMessage,
		arg.ConversationID,
		arg.ThreadID,
		arg.Sequence,
		arg.Author,
		arg.MessageText,
		arg.PostedAt,
	)
	return err
}

const applyConversationCreatedProjection = `-- name: ApplyConversationCreatedProjection :exec
INSERT INTO conversation_projection (
    id, resource_url
) VALUES (
    $1, $2
)
ON CONFLICT (id) DO UPDATE SET
    resource_url = EXCLUDED.resource_url
`

type ApplyConversationCreatedProjectionParams struct {
	ID          string
	ResourceUrl string
}

func (q *Queries) ApplyConversationCreatedProjection(ctx context.Context, arg ApplyConversationCreatedProjectionParams) error {
	_, err := q.db.Exec(ctx, applyConversationCreatedProjection, arg.ID, arg.ResourceUrl)
	return err
}

const applyThreadStartedProjection = `-- name: ApplyThreadStartedProjection :exec
INSERT INTO conversation_projection_threads (
    id, conversation_id, sequence, title, participants
) VALUES (
    $1, $2, $3, $4, $5
)
`

type ApplyThreadStartedProjectionParams struct {
	ID             string
	ConversationID string
	Sequence       int64
	Title          string
	Participants   []string
}

// No ON CONFLICT here, deliberately: (conversation_id, id) is the table's
// primary key, so a genuine collision - the same thread id landing twice
// against the same conversation with different data - fails loudly as a
// unique-violation error instead of silently no-opping.
func (q *Queries) ApplyThreadStartedProjection(ctx context.Context, arg ApplyThreadStartedProjectionParams) error {
	_, err := q.db.Exec(ctx, applyThreadStartedProjection,
		arg.ID,
		arg.ConversationID,
		arg.Sequence,
		arg.Title,
		arg.Participants,
	)
	return err
}

const conversationProjectionExists = `-- name: ConversationProjectionExists :one
SELECT EXISTS (
    SELECT 1 FROM conversation_projection_threads WHERE conversation_id = $1
)
`

func (q *Queries) ConversationProjectionExists(ctx context.Context, conversationID string) (bool, error) {
	row := q.db.QueryRow(ctx, conversationProjectionExists, conversationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getConversationProjection = `-- name: GetConversationProjection :one
SELECT id, resource_url
FROM conversation_projection
WHERE id = $1
`

func (q *Queries) GetConversationProjection(ctx context.Context, id string) (ConversationProjection, error) {
	row := q.db.QueryRow(ctx, getConversationProjection, id)
	var i ConversationProjection
	err := row.Scan(&i.ID, &i.ResourceUrl)
	return i, err
}

const getProjectionCheckpoint = `-- name: GetProjectionCheckpoint :one
SELECT sequence FROM projection_checkpoint LIMIT 1
`

func (q *Queries) GetProjectionCheckpoint(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getProjectionCheckpoint)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const listConversationIDsByParticipant = `-- name: ListConversationIDsByParticipant :many
SELECT cp.id AS conversation_id,
       COALESCE(
           MAX(cpm.posted_at) FILTER (WHERE cpt2.participants @> ARRAY[$1::text]),
           '-infinity'::timestamptz
       ) AS latest_at
FROM conversation_projection cp
JOIN conversation_projection_threads cpt ON cpt.conversation_id = cp.id
     AND cpt.participants @> ARRAY[$1::text]
LEFT JOIN conversation_projection_threads cpt2 ON cpt2.conversation_id = cp.id
     AND cpt2.participants @> ARRAY[$1::text]
LEFT JOIN conversation_projection_messages cpm ON cpm.conversation_id = cpt2.conversation_id
     AND cpm.thread_id = cpt2.id
GROUP BY cp.id
ORDER BY latest_at DESC
`

type ListConversationIDsByParticipantRow struct {
	ConversationID string
	LatestAt       interface{}
}

// Returns distinct conversation IDs where the participant appears in at
// least one thread, ordered by the latest message posted to any of the
// participant's visible threads within that conversation (most-recently-
// active first) - rule 3 of "get conversations by participant".
func (q *Queries) ListConversationIDsByParticipant(ctx context.Context, dollar_1 string) ([]ListConversationIDsByParticipantRow, error) {
	rows, err := q.db.Query(ctx, listConversationIDsByParticipant, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationIDsByParticipantRow
	for rows.Next() {
		var i ListConversationIDsByParticipantRow
		if err := rows.Scan(&i.ConversationID, &i.LatestAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationProjectionMessages = `-- name: ListConversationProjectionMessages :many
SELECT thread_id, sequence, author, message_text, posted_at
FROM conversation_projection_messages
WHERE conversation_id = $1
ORDER BY sequence
`

type ListConversationProjectionMessagesRow struct {
	ThreadID    string
	Sequence    int64
	Author      string
	MessageText string
	PostedAt    pgtype.Timestamptz
}

func (q *Queries) ListConversationProjectionMessages(ctx context.Context, conversationID string) ([]ListConversationProjectionMessagesRow, error) {
	rows, err := q.db.Query(ctx, listConversationProjectionMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationProjectionMessagesRow
	for rows.Next() {
		var i ListConversationProjectionMessagesRow
		if err := rows.Scan(
			&i.ThreadID,
			&i.Sequence,
			&i.Author,
			&i.MessageText,
			&i.PostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationProjectionThreads = `-- name: ListConversationProjectionThreads :many
SELECT id, title, participants
FROM conversation_projection_threads
WHERE conversation_id = $1
ORDER BY sequence
`

type ListConversationProjectionThreadsRow struct {
	ID           string
	Title        string
	Participants []string
}

func (q *Queries) ListConversationProjectionThreads(ctx context.Context, conversationID string) ([]ListConversationProjectionThreadsRow, error) {
	rows, err := q.db.Query(ctx, listConversationProjectionThreads, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationProjectionThreadsRow
	for rows.Next() {
		var i ListConversationProjectionThreadsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Participants); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantMessagesForConversation = `-- name: ListParticipantMessagesForConversation :many
SELECT cpm.thread_id, cpm.sequence, cpm.author, cpm.message_text, cpm.posted_at
FROM conversation_projection_messages cpm
WHERE cpm.conversation_id = $1
  AND cpm.thread_id IN (
      SELECT cpt.id FROM conversation_projection_threads cpt
      WHERE cpt.conversation_id = $1
        AND cpt.participants @> ARRAY[$2::text]
  )
ORDER BY cpm.sequence
`

type ListParticipantMessagesForConversationParams struct {
	ConversationID string
	Column2        string
}

type ListParticipantMessagesForConversationRow struct {
	ThreadID    string
	Sequence    int64
	Author      string
	MessageText string
	PostedAt    pgtype.Timestamptz
}

// Returns all messages for threads in a conversation that the participant
// is part of, in posting order.
func (q *Queries) ListParticipantMessagesForConversation(ctx context.Context, arg ListParticipantMessagesForConversationParams) ([]ListParticipantMessagesForConversationRow, error) {
	rows, err := q.db.Query(ctx, listParticipantMessagesForConversation, arg.ConversationID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParticipantMessagesForConversationRow
	for rows.Next() {
		var i ListParticipantMessagesForConversationRow
		if err := rows.Scan(
			&i.ThreadID,
			&i.Sequence,
			&i.Author,
			&i.MessageText,
			&i.PostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantThreadsForConversation = `-- name: ListParticipantThreadsForConversation :many
SELECT id, title, participants
FROM conversation_projection_threads
WHERE conversation_id = $1
  AND participants @> ARRAY[$2::text]
ORDER BY sequence
`

type ListParticipantThreadsForConversationParams struct {
	ConversationID string
	Column2        string
}

type ListParticipantThreadsForConversationRow struct {
	ID           string
	Title        string
	Participants []string
}

// Returns all threads in a conversation that the participant is part of,
// in creation order (rule 2 of "get conversations by participant").
func (q *Queries) ListParticipantThreadsForConversation(ctx context.Context, arg ListParticipantThreadsForConversationParams) ([]ListParticipantThreadsForConversationRow, error) {
	rows, err := q.db.Query(ctx, listParticipantThreadsForConversation, arg.ConversationID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParticipantThreadsForConversationRow
	for rows.Next() {
		var i ListParticipantThreadsForConversationRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Participants); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeConversationProjectionThreadParticipant = `-- name: RemoveConversationProjectionThreadParticipant :exec
UPDATE conversation_projection_threads
SET participants = array_remove(participants, $3::text)
WHERE conversation_id = $1 AND id = $2
`

type RemoveConversationProjectionThreadParticipantParams struct {
	ConversationID string
	ID             string
	Participant    string
}

func (q *Queries) RemoveConversationProjectionThreadParticipant(ctx context.Context, arg RemoveConversationProjectionThreadParticipantParams) error {
	_, err := q.db.Exec(ctx, removeConversationProjectionThreadParticipant, arg.ConversationID, arg.ID, arg.Participant)
	return err
}

const setProjectionCheckpoint = `-- name: SetProjectionCheckpoint :exec
UPDATE projection_checkpoint SET sequence = $1 WHERE sequence < $1
`

func (q *Queries) SetProjectionCheckpoint(ctx context.Context, sequence int64) error {
	_, err := q.db.Exec(ctx, setProjectionCheckpoint, sequence)
	return err
}
