// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation_events.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEvent = `-- name: InsertEvent :one
INSERT INTO conversation_events (
    event_type, conversation_id, occurred_at, payload
) VALUES (
    $1, $2, $3, $4
)
RETURNING sequence
`

type InsertEventParams struct {
	EventType      string
	ConversationID string
	OccurredAt     pgtype.Timestamptz
	Payload        []byte
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.EventType,
		arg.ConversationID,
		arg.OccurredAt,
		arg.Payload,
	)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const listConversationEvents = `-- name: ListConversationEvents :many
SELECT sequence, event_type, conversation_id, occurred_at, payload
FROM conversation_events
WHERE conversation_id = $1
ORDER BY sequence
`

func (q *Queries) ListConversationEvents(ctx context.Context, conversationID string) ([]ConversationEvent, error) {
	rows, err := q.db.Query(ctx, listConversationEvents, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationEvent
	for rows.Next() {
		var i ConversationEvent
		if err := rows.Scan(
			&i.Sequence,
			&i.EventType,
			&i.ConversationID,
			&i.OccurredAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
