// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ConversationEvent struct {
	Sequence       int64
	ConversationID string
	ThreadID       string
	MessageID      string
	Creator        pgtype.Text
	ResourceUrl    pgtype.Text
	ThreadTitle    pgtype.Text
	Author         string
	Recipients     []string
	MessageText    string
	OccurredAt     pgtype.Timestamptz
	EventType      string
}

type ConversationOutbox struct {
	Sequence       int64
	ConversationID string
	ThreadID       string
	MessageID      string
	Creator        pgtype.Text
	ResourceUrl    pgtype.Text
	ThreadTitle    pgtype.Text
	Author         string
	Recipients     []string
	MessageText    string
	OccurredAt     pgtype.Timestamptz
	DoneAt         pgtype.Timestamptz
	EventType      string
}

type ConversationProjection struct {
	ID           string
	ResourceUrl  string
	ThreadID     string
	ThreadTitle  string
	Participants []string
}

type ConversationProjectionMessage struct {
	ConversationID string
	Sequence       int64
	Author         string
	MessageText    string
	PostedAt       pgtype.Timestamptz
}

type ProjectionCheckpoint struct {
	ID       bool
	Sequence int64
}
