// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ConversationEvent struct {
	Sequence       int64
	ConversationID string
	ThreadID       string
	MessageID      string
	Creator        string
	ResourceUrl    string
	ThreadTitle    string
	Author         string
	Recipients     []string
	MessageText    string
	OccurredAt     pgtype.Timestamptz
}

type ConversationOutbox struct {
	Sequence       int64
	ConversationID string
	ThreadID       string
	MessageID      string
	Creator        string
	ResourceUrl    string
	ThreadTitle    string
	Author         string
	Recipients     []string
	MessageText    string
	OccurredAt     pgtype.Timestamptz
	DoneAt         pgtype.Timestamptz
}

type ConversationProjection struct {
	ID              string
	ResourceUrl     string
	ThreadID        string
	ThreadTitle     string
	Recipients      []string
	MessageAuthor   string
	MessageText     string
	MessagePostedAt pgtype.Timestamptz
}

type ProjectionCheckpoint struct {
	ID       bool
	Sequence int64
}
