// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ConversationEvent struct {
	Sequence       int64
	EventType      string
	ConversationID string
	OccurredAt     pgtype.Timestamptz
	Payload        []byte
}

type ConversationOutbox struct {
	Sequence       int64
	EventType      string
	ConversationID string
	OccurredAt     pgtype.Timestamptz
	Payload        []byte
	DoneAt         pgtype.Timestamptz
}

type ConversationProjection struct {
	ID          string
	ResourceUrl string
}

type ConversationProjectionMessage struct {
	ConversationID string
	Sequence       int64
	Author         string
	MessageText    string
	PostedAt       pgtype.Timestamptz
	ThreadID       string
}

type ConversationProjectionThread struct {
	ID             string
	ConversationID string
	Sequence       int64
	Title          string
	Participants   []string
}

type ProjectionCheckpoint struct {
	ID       bool
	Sequence int64
}
