// Package apiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package apiclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// AddThreadRequest All four fields are required by CE's domain rules, but none are marked required at the schema level - the same posture as StartConversationRequest: a missing key and a present-but-empty value are meaningfully different (see the "add a thread to a conversation" story), so all fields stay optional/pointer here.
type AddThreadRequest struct {
	Author      *string   `json:"author,omitempty"`
	Message     *string   `json:"message,omitempty"`
	Recipients  *[]string `json:"recipients,omitempty"`
	ThreadTitle *string   `json:"threadTitle,omitempty"`
}

// Conversation defines model for Conversation.
type Conversation struct {
	Id          string `json:"id"`
	ResourceUrl string `json:"resourceUrl"`

	// Threads One entry per thread the conversation has, in creation order: the original thread first, then each added thread in the order it was started (see the "add a thread to a conversation" story) - superseding the single "thread" field a conversation used to expose.
	Threads []Thread `json:"threads"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Event One flat shape reused across all three event kinds (see the "list a conversation's events" story, rule 5) - only the fields relevant to type are populated, the rest omitted entirely rather than sent as null/empty.
type Event struct {
	// Author Populated for a ThreadStarted or MessagePosted event.
	Author *string `json:"author,omitempty"`

	// Creator Populated for a ConversationCreated event.
	Creator *string `json:"creator,omitempty"`

	// MessageId Populated for a MessagePosted event.
	MessageId *string `json:"messageId,omitempty"`

	// MessageText Populated for a MessagePosted event.
	MessageText *string   `json:"messageText,omitempty"`
	OccurredAt  time.Time `json:"occurredAt"`

	// ParticipantId Populated for a ParticipantAdded or ParticipantRemoved event.
	ParticipantId *string `json:"participantId,omitempty"`

	// Recipients Populated for a ThreadStarted event.
	Recipients *[]string `json:"recipients,omitempty"`

	// ResourceUrl Populated for a ConversationCreated event.
	ResourceUrl *string `json:"resourceUrl,omitempty"`
	Sequence    int64   `json:"sequence"`

	// ThreadId Populated for a ThreadStarted or MessagePosted event.
	ThreadId *string `json:"threadId,omitempty"`

	// ThreadTitle Populated for a ThreadStarted event.
	ThreadTitle *string `json:"threadTitle,omitempty"`

	// Type The event's kind: "ConversationCreated", "ThreadStarted" or "MessagePosted".
	Type string `json:"type"`
}

// Message defines model for Message.
type Message struct {
	Author   string    `json:"author"`
	PostedAt time.Time `json:"postedAt"`
	Text     string    `json:"text"`
}

// ReplyToThreadRequest Both fields are required by CE's domain rules, but neither is marked required at the schema level - the same posture as StartConversationRequest: a missing key and a present-but-empty value are meaningfully different (see "reply to a thread" rule 1), so both fields stay optional/pointer here.
type ReplyToThreadRequest struct {
	Author *string `json:"author,omitempty"`
	Text   *string `json:"text,omitempty"`
}

// StartConversationRequest All five fields are required by CE's domain rules, but none are marked required at the schema level - a missing key and a present-but-empty value are meaningfully different (see the "start a conversation" story), and the distinction is only preserved if the generated type can tell "absent" from "zero value", i.e. every field stays optional/pointer here.
type StartConversationRequest struct {
	Author      *string   `json:"author,omitempty"`
	Message     *string   `json:"message,omitempty"`
	Recipients  *[]string `json:"recipients,omitempty"`
	ResourceUrl *string   `json:"resourceUrl,omitempty"`
	ThreadTitle *string   `json:"threadTitle,omitempty"`
}

// Thread defines model for Thread.
type Thread struct {
	Id       string    `json:"id"`
	Messages []Message `json:"messages"`

	// Participants The union of the thread's original author and its recipients (see the "thread participants" story) - unordered, a set not a sequence.
	Participants []string `json:"participants"`
	Title        string   `json:"title"`
}

// GetConversationsByParticipantParams defines parameters for GetConversationsByParticipant.
type GetConversationsByParticipantParams struct {
	ParticipantId string `form:"participant_id" json:"participant_id"`
}

// GetConversationParams defines parameters for GetConversation.
type GetConversationParams struct {
	// After A sequence number from a prior write's Location header - the response is 202 until the projection's checkpoint reaches it
	After *int64 `form:"after,omitempty" json:"after,omitempty"`
}

// StartConversationJSONRequestBody defines body for StartConversation for application/json ContentType.
type StartConversationJSONRequestBody = StartConversationRequest

// AddThreadJSONRequestBody defines body for AddThread for application/json ContentType.
type AddThreadJSONRequestBody = AddThreadRequest

// ReplyToThreadJSONRequestBody defines body for ReplyToThread for application/json ContentType.
type ReplyToThreadJSONRequestBody = ReplyToThreadRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetConversationsByParticipant request
	GetConversationsByParticipant(ctx context.Context, params *GetConversationsByParticipantParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StartConversationWithBody request with any body
	StartConversationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	StartConversation(ctx context.Context, body StartConversationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListConversationEvents request
	ListConversationEvents(ctx context.Context, conversationId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddThreadWithBody request with any body
	AddThreadWithBody(ctx context.Context, conversationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddThread(ctx context.Context, conversationId string, body AddThreadJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReplyToThreadWithBody request with any body
	ReplyToThreadWithBody(ctx context.Context, conversationId string, threadId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ReplyToThread(ctx context.Context, conversationId string, threadId string, body ReplyToThreadJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RemoveThreadParticipant request
	RemoveThreadParticipant(ctx context.Context, conversationId string, threadId string, participantId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddThreadParticipant request
	AddThreadParticipant(ctx context.Context, conversationId string, threadId string, participantId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetConversation request
	GetConversation(ctx context.Context, id string, params *GetConversationParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetConversationsByParticipant(ctx context.Context, params *GetConversationsByParticipantParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetConversationsByParticipantRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartConversationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartConversationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartConversation(ctx context.Context, body StartConversationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartConversationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListConversationEvents(ctx context.Context, conversationId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListConversationEventsRequest(c.Server, conversationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddThreadWithBody(ctx context.Context, conversationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddThreadRequestWithBody(c.Server, conversationId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddThread(ctx context.Context, conversationId string, body AddThreadJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddThreadRequest(c.Server, conversationId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReplyToThreadWithBody(ctx context.Context, conversationId string, threadId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplyToThreadRequestWithBody(c.Server, conversationId, threadId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReplyToThread(ctx context.Context, conversationId string, threadId string, body ReplyToThreadJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplyToThreadRequest(c.Server, conversationId, threadId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RemoveThreadParticipant(ctx context.Context, conversationId string, threadId string, participantId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRemoveThreadParticipantRequest(c.Server, conversationId, threadId, participantId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddThreadParticipant(ctx context.Context, conversationId string, threadId string, participantId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddThreadParticipantRequest(c.Server, conversationId, threadId, participantId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetConversation(ctx context.Context, id string, params *GetConversationParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetConversationRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetConversationsByParticipantRequest generates requests for GetConversationsByParticipant
func NewGetConversationsByParticipantRequest(server string, params *GetConversationsByParticipantParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/conversations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "participant_id", params.ParticipantId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStartConversationRequest calls the generic StartConversation builder with application/json body
func NewStartConversationRequest(server string, body StartConversationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewStartConversationRequestWithBody(server, "application/json", bodyReader)
}

// NewStartConversationRequestWithBody generates requests for StartConversation with any type of body
func NewStartConversationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/conversations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListConversationEventsRequest generates requests for ListConversationEvents
func NewListConversationEventsRequest(server string, conversationId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "conversationId", conversationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/conversations/%s/events", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddThreadRequest calls the generic AddThread builder with application/json body
func NewAddThreadRequest(server string, conversationId string, body AddThreadJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddThreadRequestWithBody(server, conversationId, "application/json", bodyReader)
}

// NewAddThreadRequestWithBody generates requests for AddThread with any type of body
func NewAddThreadRequestWithBody(server string, conversationId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "conversationId", conversationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/conversations/%s/threads", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewReplyToThreadRequest calls the generic ReplyToThread builder with application/json body
func NewReplyToThreadRequest(server string, conversationId string, threadId string, body ReplyToThreadJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReplyToThreadRequestWithBody(server, conversationId, threadId, "application/json", bodyReader)
}

// NewReplyToThreadRequestWithBody generates requests for ReplyToThread with any type of body
func NewReplyToThreadRequestWithBody(server string, conversationId string, threadId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "conversationId", conversationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "threadId", threadId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/conversations/%s/threads/%s/messages", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRemoveThreadParticipantRequest generates requests for RemoveThreadParticipant
func NewRemoveThreadParticipantRequest(server string, conversationId string, threadId string, participantId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "conversationId", conversationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "threadId", threadId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "participantId", participantId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/conversations/%s/threads/%s/participants/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddThreadParticipantRequest generates requests for AddThreadParticipant
func NewAddThreadParticipantRequest(server string, conversationId string, threadId string, participantId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "conversationId", conversationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "threadId", threadId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "participantId", participantId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/conversations/%s/threads/%s/participants/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetConversationRequest generates requests for GetConversation
func NewGetConversationRequest(server string, id string, params *GetConversationParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/conversations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.After != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "after", *params.After, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetConversationsByParticipantWithResponse request
	GetConversationsByParticipantWithResponse(ctx context.Context, params *GetConversationsByParticipantParams, reqEditors ...RequestEditorFn) (*GetConversationsByParticipantResponse, error)

	// StartConversationWithBodyWithResponse request with any body
	StartConversationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StartConversationResponse, error)

	StartConversationWithResponse(ctx context.Context, body StartConversationJSONRequestBody, reqEditors ...RequestEditorFn) (*StartConversationResponse, error)

	// ListConversationEventsWithResponse request
	ListConversationEventsWithResponse(ctx context.Context, conversationId string, reqEditors ...RequestEditorFn) (*ListConversationEventsResponse, error)

	// AddThreadWithBodyWithResponse request with any body
	AddThreadWithBodyWithResponse(ctx context.Context, conversationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddThreadResponse, error)

	AddThreadWithResponse(ctx context.Context, conversationId string, body AddThreadJSONRequestBody, reqEditors ...RequestEditorFn) (*AddThreadResponse, error)

	// ReplyToThreadWithBodyWithResponse request with any body
	ReplyToThreadWithBodyWithResponse(ctx context.Context, conversationId string, threadId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReplyToThreadResponse, error)

	ReplyToThreadWithResponse(ctx context.Context, conversationId string, threadId string, body ReplyToThreadJSONRequestBody, reqEditors ...RequestEditorFn) (*ReplyToThreadResponse, error)

	// RemoveThreadParticipantWithResponse request
	RemoveThreadParticipantWithResponse(ctx context.Context, conversationId string, threadId string, participantId string, reqEditors ...RequestEditorFn) (*RemoveThreadParticipantResponse, error)

	// AddThreadParticipantWithResponse request
	AddThreadParticipantWithResponse(ctx context.Context, conversationId string, threadId string, participantId string, reqEditors ...RequestEditorFn) (*AddThreadParticipantResponse, error)

	// GetConversationWithResponse request
	GetConversationWithResponse(ctx context.Context, id string, params *GetConversationParams, reqEditors ...RequestEditorFn) (*GetConversationResponse, error)
}

type GetConversationsByParticipantResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Conversation
}

// Status returns HTTPResponse.Status
func (r GetConversationsByParticipantResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetConversationsByParticipantResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetConversationsByParticipantResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type StartConversationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
}

// Status returns HTTPResponse.Status
func (r StartConversationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StartConversationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r StartConversationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListConversationEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]Event
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r ListConversationEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListConversationEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListConversationEventsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AddThreadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r AddThreadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddThreadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AddThreadResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ReplyToThreadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON403      *Error
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r ReplyToThreadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReplyToThreadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ReplyToThreadResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RemoveThreadParticipantResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r RemoveThreadParticipantResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RemoveThreadParticipantResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RemoveThreadParticipantResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AddThreadParticipantResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r AddThreadParticipantResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddThreadParticipantResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AddThreadParticipantResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetConversationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Conversation
	JSON404      *Error
}

// Status returns HTTPResponse.Status
func (r GetConversationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetConversationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetConversationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetConversationsByParticipantWithResponse request returning *GetConversationsByParticipantResponse
func (c *ClientWithResponses) GetConversationsByParticipantWithResponse(ctx context.Context, params *GetConversationsByParticipantParams, reqEditors ...RequestEditorFn) (*GetConversationsByParticipantResponse, error) {
	rsp, err := c.GetConversationsByParticipant(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetConversationsByParticipantResponse(rsp)
}

// StartConversationWithBodyWithResponse request with arbitrary body returning *StartConversationResponse
func (c *ClientWithResponses) StartConversationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*StartConversationResponse, error) {
	rsp, err := c.StartConversationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartConversationResponse(rsp)
}

func (c *ClientWithResponses) StartConversationWithResponse(ctx context.Context, body StartConversationJSONRequestBody, reqEditors ...RequestEditorFn) (*StartConversationResponse, error) {
	rsp, err := c.StartConversation(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartConversationResponse(rsp)
}

// ListConversationEventsWithResponse request returning *ListConversationEventsResponse
func (c *ClientWithResponses) ListConversationEventsWithResponse(ctx context.Context, conversationId string, reqEditors ...RequestEditorFn) (*ListConversationEventsResponse, error) {
	rsp, err := c.ListConversationEvents(ctx, conversationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListConversationEventsResponse(rsp)
}

// AddThreadWithBodyWithResponse request with arbitrary body returning *AddThreadResponse
func (c *ClientWithResponses) AddThreadWithBodyWithResponse(ctx context.Context, conversationId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddThreadResponse, error) {
	rsp, err := c.AddThreadWithBody(ctx, conversationId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddThreadResponse(rsp)
}

func (c *ClientWithResponses) AddThreadWithResponse(ctx context.Context, conversationId string, body AddThreadJSONRequestBody, reqEditors ...RequestEditorFn) (*AddThreadResponse, error) {
	rsp, err := c.AddThread(ctx, conversationId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddThreadResponse(rsp)
}

// ReplyToThreadWithBodyWithResponse request with arbitrary body returning *ReplyToThreadResponse
func (c *ClientWithResponses) ReplyToThreadWithBodyWithResponse(ctx context.Context, conversationId string, threadId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReplyToThreadResponse, error) {
	rsp, err := c.ReplyToThreadWithBody(ctx, conversationId, threadId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReplyToThreadResponse(rsp)
}

func (c *ClientWithResponses) ReplyToThreadWithResponse(ctx context.Context, conversationId string, threadId string, body ReplyToThreadJSONRequestBody, reqEditors ...RequestEditorFn) (*ReplyToThreadResponse, error) {
	rsp, err := c.ReplyToThread(ctx, conversationId, threadId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReplyToThreadResponse(rsp)
}

// RemoveThreadParticipantWithResponse request returning *RemoveThreadParticipantResponse
func (c *ClientWithResponses) RemoveThreadParticipantWithResponse(ctx context.Context, conversationId string, threadId string, participantId string, reqEditors ...RequestEditorFn) (*RemoveThreadParticipantResponse, error) {
	rsp, err := c.RemoveThreadParticipant(ctx, conversationId, threadId, participantId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRemoveThreadParticipantResponse(rsp)
}

// AddThreadParticipantWithResponse request returning *AddThreadParticipantResponse
func (c *ClientWithResponses) AddThreadParticipantWithResponse(ctx context.Context, conversationId string, threadId string, participantId string, reqEditors ...RequestEditorFn) (*AddThreadParticipantResponse, error) {
	rsp, err := c.AddThreadParticipant(ctx, conversationId, threadId, participantId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddThreadParticipantResponse(rsp)
}

// GetConversationWithResponse request returning *GetConversationResponse
func (c *ClientWithResponses) GetConversationWithResponse(ctx context.Context, id string, params *GetConversationParams, reqEditors ...RequestEditorFn) (*GetConversationResponse, error) {
	rsp, err := c.GetConversation(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetConversationResponse(rsp)
}

// ParseGetConversationsByParticipantResponse parses an HTTP response from a GetConversationsByParticipantWithResponse call
func ParseGetConversationsByParticipantResponse(rsp *http.Response) (*GetConversationsByParticipantResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetConversationsByParticipantResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Conversation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseStartConversationResponse parses an HTTP response from a StartConversationWithResponse call
func ParseStartConversationResponse(rsp *http.Response) (*StartConversationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StartConversationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseListConversationEventsResponse parses an HTTP response from a ListConversationEventsWithResponse call
func ParseListConversationEventsResponse(rsp *http.Response) (*ListConversationEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListConversationEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Event
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseAddThreadResponse parses an HTTP response from a AddThreadWithResponse call
func ParseAddThreadResponse(rsp *http.Response) (*AddThreadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddThreadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseReplyToThreadResponse parses an HTTP response from a ReplyToThreadWithResponse call
func ParseReplyToThreadResponse(rsp *http.Response) (*ReplyToThreadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReplyToThreadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseRemoveThreadParticipantResponse parses an HTTP response from a RemoveThreadParticipantWithResponse call
func ParseRemoveThreadParticipantResponse(rsp *http.Response) (*RemoveThreadParticipantResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RemoveThreadParticipantResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseAddThreadParticipantResponse parses an HTTP response from a AddThreadParticipantWithResponse call
func ParseAddThreadParticipantResponse(rsp *http.Response) (*AddThreadParticipantResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddThreadParticipantResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetConversationResponse parses an HTTP response from a GetConversationWithResponse call
func ParseGetConversationResponse(rsp *http.Response) (*GetConversationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetConversationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Conversation
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
